name: Production_deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: php-actions/composer@v6
        with:
          args: --ignore-platform-req=ext-gd


      - name: PHPUnit Tests
        uses: php-actions/phpunit@v3
        with:
          version: 9.6
          php_version: 8.1
          bootstrap: vendor/autoload.php
          configuration: phpunit.xml
          args: --coverage-text

      - run: vendor/bin/phpunit




