name: Production_deploy
on:
  push:
    branches: [main]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Filesystem
        run: composer require league/flysystem-aws-s3-v3 "^3.0" --with-all-dependencies

      - name: Dependencies
        uses: php-actions/composer@v6
        with:
          args: --ignore-platform-req=ext-gd
            --ignore-platform-req=ext-zip

      - name: Copy .env
        run: cp .env.example .env

      - name: Generate app key
        run: php artisan key:generate

      - name: Build and run Docker containers
        run: docker-compose -f docker-compose.dev.yml up -d
        working-directory: .

      - name: Permissions for storage
        run: docker exec app_new chmod -R 777 storage

      - name: Execute tests (Unit and Feature tests) via PHPUnit
        run: php artisan test --filter UserAuthenticationTest


