name: Production_deploy
on:
  push:
    branches: [main]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    name: Build & Test
    runs-on: ubuntu-latest


    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and run Docker containers
        run: docker-compose -f docker-compose.dev.yml up -d
        working-directory: .

      - name: Dependencies
        uses: php-actions/composer@v6
        with:
          args: --ignore-platform-req=ext-gd
            --ignore-platform-req=ext-zip
            --prefer-dist
            --no-progress

      - name: Copy .env
        run: cp .env.example .env

      - name: Generate app key
        run: php artisan key:generate

      - name: Permissions for storage
        run: docker exec app_new chmod -R 777 storage

      - name: Execute PHPUnit Tests
        uses: php-actions/phpunit@v3
        with:
          version: 9.6
          php_version: 8.1
          bootstrap: vendor/autoload.php
          configuration: phpunit.xml
          args: --coverage-text

      - name : Additional runner
        run: vendor/bin/phpunit

      - name: Execute tests (Unit and Feature tests) via PHPUnit
        run: php artisan test --parallel



