name: Production_deploy
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]


jobs:
  deploy:
    name: Build & Testing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
            fetch-depth: 0
            token: ${{ secrets.GH_PAT }}

      - name: Dependencies
        uses: php-actions/composer@v6
        with:
          args: --ignore-platform-req=ext-gd
            --ignore-platform-req=ext-zip

      - name: Link to the storage
        run: php artisan storage:link

      - name: Clear config
        run: php artisan config:clear

      - name: Copy .env
        run: cp .env.example .env

      - name: Generate app key
        run: php artisan key:generate

      - name: Build and run Docker containers
        run: docker-compose -f docker-compose.dev.yml up -d
        working-directory: .

      - name: Permissions for storage
        run: docker exec app_new_test chmod -R 755 storage

      - name: Execute tests via PHPUnit
        id: tests
        run: php artisan test --filter Integration || echo "FAILED=true" >> $GITHUB_ENV

      - name: Revert Commit if Tests Fail
        if: ${{ env.FAILED == 'true' }}
        run: |
          git config user.name 'GitHub Actions'
          git config user.email 'actions@github.com'
          git reset --hard HEAD~1
          git push --force
        env:
          GH_PAT: ${{ secrets.GH_PAT }}

