name: Production_deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Connect via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            set -e
            cd /data/ifal-backend
            git checkout main
            git pull origin main
            docker compose up -d --build
            docker restart app
      
      - name: PHPUnit Tests
        uses: php-actions/phpunit@v3
        with:
          version: 9.6
          bootstrap: vendor/autoload.php
          configuration: phpunit.xml
          args: --coverage-text
      - run: vendor/bin/phpunit

