name: Production_deploy
on:
  push:
    branches: [main]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Dependencies
        uses: php-actions/composer@v6
        with:
          args: --ignore-platform-req=ext-gd
            --ignore-platform-req=ext-zip

      - name: Link to the storage
        run: php artisan storage:link

      - name: Clear config
        run: php artisan config:clear

      - name: Copy .env
        run: cp .env.example .env

      - name: Generate app key
        run: php artisan key:generate

      - name: Build and run Docker containers
        run: docker-compose -f docker-compose.dev.yml up -d
        working-directory: .

      - name: Permissions for storage
        run: docker exec app_new_test chmod -R 755 storage

      - name: Execute tests via PHPUnit
        run: php artisan test --filter Integration
        continue-on-error: false
        if: |
          if [ $? -eq 0 ]; then
            echo "Tests passed. Proceeding with merge..."
          else
            echo "Tests failed. Preventing merge."
              PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          API_URL="https://api.github.com/repos/${GITHUB_REPOSITORY}/issues/${PR_NUMBER}/comments"
          COMMENT="Tests failed. Merging is not allowed until tests pass."
          TOKEN=${{ secrets.GITHUB_TOKEN }}
          curl -X POST -d "{\"body\": \"$COMMENT\"}" -H "Authorization: token $TOKEN" -H "Content-Type: application/json" $API_URL
          # Установка статуса "failure" для GitHub Actions
          gh status create "Tests failed" -c "$GITHUB_SHA" -d "Tests failed" -s failure
          exit 1

          fi


