name: Production_deploy
on:
  push:
    branches: [main]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    name: Build & Test
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: laravel
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and run Docker containers
        run: docker-compose -f docker-compose.dev.yml up -d

      - name: Copy .env
        run: cp .env.example .env

      - name: Dependencies
        uses: php-actions/composer@v6
        with:
            args: --ignore-platform-req=ext-gd
                  --ignore-platform-req=ext-zip

      - name: Generate app key
        run: php artisan key:generate

      - name: Permissions for storage
        run: docker exec app_new chmod -R 777 storage

      - name: Run migrations and seeders
        run: docker exec app_new artisan migrate:fresh --seed --force
        env:
            DB_HOST: db
            DB_PORT: 3306
            DB_DATABASE: laravel
            DB_USERNAME: root
            DB_PASSWORD: root

      - name: Execute PHPUnit Tests
        uses: php-actions/phpunit@v3
        with:
          version: 9.6
          php_version: 8.1
          bootstrap: vendor/autoload.php
          configuration: phpunit.xml
          args: --coverage-text

      - name : Additional runner
        run: vendor/bin/phpunit

      - name: Execute tests (Unit and Feature tests) via PHPUnit
        run: php artisan test --parallel



