name: Production_deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        run: vendor/bin/phpunit
      - name: PHPUnit Tests
        uses: php-actions/phpunit@v3
        env:
          TEST_NAME: Scarlett
        with:
          bootstrap: autoload.php
          configuration: phpunit.xml
          args: --coverage-text

